### ISSUE TITLE
How can I add the sequential download option to this script?

### ISSUE THREAD

**Issue by jwash11** [r12habh/Torrent-To-Google-Drive-Downloader-v3#11]
sequential_download(True) 
http://libtorrent.org/reference-Torrent_Handle.html#flags-set-flags-unset-flags
http://libtorrent.org/reference-Core.html#torrent_flags_t

**Comment by ethanaobrien** [comment]
Add the code
`handle.set_sequential_download(1)`

right after the 
`handle = lt.add_magnet_uri(ses, link, params)`

To make this
```
handle = lt.add_magnet_uri(ses, link, params)
handle.set_sequential_download(0)
```

I used v3 to test. I am making a v4 that will have this option.
