### ISSUE TITLE
download as zip file

### ISSUE THREAD

**Issue by nutcyy87** [r12habh/Torrent-To-Google-Drive-Downloader-v3#16]
**hi brother** 
**when i download torrent file,it save as a folder 
and if i want dowload folder,google drive zips folder and i can download it as zip file but it take more time
is any way that i download torrent file as zip file to drive directly?**

**Comment by r12habh** [comment]
Manual steps to download torrent file as a zipped file from gDrive:
1. Change the download location to the colab's local destination
`'save_path': '/content/'`

2. use `!apt-get install zip` & then `zip -r file_downloaded.zip /content/file_downloaded`

3. move the zipped file to google drive `mv file_downloaded.zip /content/drive/My Drive/Torrent/file_downloaded.zip`

**Comment by r12habh** [comment]
@ethanaobrien

**Comment by ethanaobrien** [comment]
We could add the script to zip the torrent, but google colab downloads files the same way mega does, also, you would need to go into the file browser and manually press download. Would this be a problem?

**Comment by r12habh** [comment]
I don't think anything will be manual everything can be done through `shell` scripts.
I just need a script to get the name of the downloaded file and then zip it (something like this)

do you have a better solution?

**Comment by ethanaobrien** [comment]
@r12habh I have most of the code written, I am having trouble with one thing.

I have tried using `handle.save_path` to get the save path of the torrent but it only returns `<bound method save_path of <libtorrent.torrent_handle object at 0x7f906d3e38d0>>`

After I can find how to get the complete path of the torrent the code is done. I have also added a few other features (I'm basically making a v4, or v3.1 or something)
