### ISSUE TITLE
Torrent stuck on "downloading metadata"

### ISSUE THREAD

**Issue by ethanaobrien** [r12habh/Torrent-To-Google-Drive-Downloader-v3#20]
Torrent stuck on "downloading metadata". What should I do. I have tried multiple links and magnets

**Comment by nHiRanZ** [comment]
+1 same here

**Comment by fahmiegerton** [comment]
Me too

**Comment by camlogical** [comment]
> Torrent stuck on "downloading metadata". What should I do. I have tried multiple links and magnets

Look at this line. `'storage_mode': lt.storage_mode_t(2),`
delete comma like the code below.
`'storage_mode': lt.storage_mode_t(2)`

**Comment by camlogical** [comment]
in dependency paste below code:
`!python -m pip install --upgrade pip setuptools wheel && python -m pip install lbry-libtorrent && pip install folium==0.2.1 && apt install python3-libtorrent`

**Comment by nHiRanZ** [comment]
@camlogical still doesn't work

**Comment by camlogical** [comment]
> @camlogical still doesn't work

Don't use V3. Use V2 instead.

**Comment by nHiRanZ** [comment]
The fixes works on the v2. Thanks @camlogical.

**Comment by nHiRanZ** [comment]
@camlogical doesn't work again. :/

**Comment by camlogical** [comment]
> @camlogical doesn't work again. :/

screenshot your error.

**Comment by nHiRanZ** [comment]
Found the issue. For some reason torrent links from YTS doesn’t work. Converted it to a magnet link and it worked.

**Comment by camlogical** [comment]
Everything has been fixed. issue should be close.

**Comment by r12habh** [comment]
Try to always use magnet link
