### ISSUE TITLE
Download speed stuck at 3.75 MB/s

### ISSUE THREAD

**Issue by faruqeclypst** [r12habh/Torrent-To-Google-Drive-Downloader-v3#27]
what should I do, almost any torrent file that is always in the process of being downloaded never gets past 10 MB / s
![image](https://user-images.githubusercontent.com/16388915/113924744-5fdcb600-9814-11eb-8961-b228642009ce.png)

**Comment by ethanaobrien** [comment]
@faruqeclypst this is not you. The torrent has to upload something from someones computer around the world. We cannot control the upload speed of other peoples internet

**Comment by faruqeclypst** [comment]
> @faruqeclypst this is not you. The torrent has to upload something from someones computer around the world. We cannot control the upload speed of other peoples internet

oh i see, sorry initially I don't really understand how it works, thanks!
